// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoMl0BzzgKa3t0hoUgZMSa1GE40sQ71Wc',
    appId: '1:182078725088:web:b8a350cd09653abefda985',
    messagingSenderId: '182078725088',
    projectId: 'sakhi-app-a2a09',
    authDomain: 'sakhi-app-a2a09.firebaseapp.com',
    storageBucket: 'sakhi-app-a2a09.appspot.com',
    measurementId: 'G-CHHCPM2J3T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATrJleK7mRSjXP6bfVN_gQKMEheGwQ2-4',
    appId: '1:182078725088:android:c4a70ad3bd7d50b4fda985',
    messagingSenderId: '182078725088',
    projectId: 'sakhi-app-a2a09',
    storageBucket: 'sakhi-app-a2a09.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9Y616tO_-z8odQ6N-LvP0lhS8vzPR5N8',
    appId: '1:182078725088:ios:8c0787186c02ee46fda985',
    messagingSenderId: '182078725088',
    projectId: 'sakhi-app-a2a09',
    storageBucket: 'sakhi-app-a2a09.appspot.com',
    iosBundleId: 'com.example.flutterPages',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9Y616tO_-z8odQ6N-LvP0lhS8vzPR5N8',
    appId: '1:182078725088:ios:a02cbd663168c4f9fda985',
    messagingSenderId: '182078725088',
    projectId: 'sakhi-app-a2a09',
    storageBucket: 'sakhi-app-a2a09.appspot.com',
    iosBundleId: 'com.example.flutterPages.RunnerTests',
  );
}
